### ISSUE TITLE
Potential Optimization (Path Parts)

### ISSUE THREAD

**Issue by chrisaxiom** [AndrewBurian/powermux#37]
`pathParts := pathPartsPool.Get().([]string)[0:0]` is only recycling the backing arrays that contain the strings; the strings themselves ([]byte) are not being recycled.  Could potentially do something here to recycle the actual strings, as the lengths will be fairly stable.

**Comment by AndrewBurian** [comment]
In the `pathParts` slice, each pointer is actually pointing to a [different slice of the same underlying `[]byte` array](https://github.com/AndrewBurian/powermux/blob/master/route.go#L92) that was [generated by `r.URL.EscapedPath()`](https://github.com/AndrewBurian/powermux/blob/master/servemux.go#L69). 

So the actual byte storage is only allocated once and needs to be done by the URL object anyways, so no getting around that. Then making slices on top of that is relatively cheap as we don't copy or reallocate storage, just add a few ~3 byte slice objects.

**Comment by chrisaxiom** [comment]
Ah yes I should have read down further.  I suppose this is as good as it gets here.
