### ISSUE TITLE
Limit Middlewares to specific Verbs

### ISSUE THREAD

**Issue by AndrewBurian** [AndrewBurian/powermux#40]
Allow middlewares to be assigned or omitted from specific verbs.

Specifically assigned is useful for instance to add access checks to only mutating verbs. Omission is useful to do things like only not applying auth for pre-flight `OPTIONS` checks since the browser won't include any headers.

Possible implementation: 
```go
// must specify all verbs this middleware applies to
func (r *Route) MiddlewareOnly(mid Middleware, verbs ...string) *Route {}

// specify any verbs the middleware should NOT apply to
func (r *Route) MiddlewareExcept(mid Middleware, verbs ...string) *Route {}
```

These functions will be in addition to the existing Middleware function:
```go
func (r *Route) Middleware(mid Middleware) *Route{}
```
which is the same as `MiddleareFor` with the full list of verbs or `MiddlewareExcept` with no verbs.

**Comment by AndrewBurian** [comment]
Also `MiddlewareFor` or `MiddlewareOnly`?

**Comment by omatvejev** [comment]
I think I prefer `MiddlewareFor`. The reason for this is that to me the `MiddlewareOnly` sounds like it would only work on one verb and not multiple verbs. Like "This middleware is applied only to POST"

**Comment by hwrdtm** [comment]
+1 `MiddlewareFor`
